add project URLs to setup.py
BEL-Public/mffpy pull request #127
Opened 2024-07-20 06:24 UTC by sappelhoff

fix for https://github.com/mne-tools/mne-python/blob/071a98fae28bd7c32c6ce357076263ef01031994/doc/sphinxext/related_software.py#L78

- xref https://github.com/mne-tools/mne-python/pull/12731

cc @larsoner @damian5710

2024-07-22 07:33 UTC, sappelhoff commented
or perhaps @ephathaway or @mscheltienne who seem to have committed to this repo before :)

2024-07-23 19:11 UTC, damian5710 requested changes
Hi @sappelhoff ! Thanks for contributing to this project. It seems that there are trailing whitespaces in line 38. Could you remove them before merging this PR please?

2024-07-23 19:11 UTC, damian5710 commented on setup.py
> +    },
```suggestion
    },
```

2024-07-23 19:29 UTC, sappelhoff commented
> it seems that there are trailing whitespaces in line 38. Could you remove them before merging this PR please?

of course! Thanks for spotting it and thanks for the code suggestion @damian5710.

2024-07-23 19:46 UTC, damian5710 approved these changes
Looks good! Thank you, @sappelhoff

2024-07-29 07:40 UTC, sappelhoff commented
@damian5710 what points are left to do to get this merged?

2024-07-30 16:34 UTC, damian5710 commented
Sorry for the delay. I'll go ahead and merge this PR now. Thanks!

2024-07-30 16:34 UTC, merged