Add(FileInfo): acquisionVersion, ampType
BEL-Public/mffpy pull request #72
Opened 2021-01-06 13:46 UTC by jusjusjus

2021-01-06 14:03 UTC, jusjusjus commented on mffpy/tests/test_xml_files.py
> +    ans = join(examples_path, 'example_2.mff', 'info.xml')
example_2.mff has acquisitionVersion and ampType, example_1.mff doesn't.

2021-01-06 22:09 UTC, ephathaway requested changes
Just a few documentation things, but otherwise looks good!

2021-01-07 09:01 UTC, jusjusjus commented on mffpy/xml_files.py
> +    def acquisitionVersion(self):
Well, if you have an idea of what that is; I don't.

2021-01-07 09:10 UTC, jusjusjus commented
Thanks for the review; I submitted more changes to the doc strings.

2021-01-11 23:26 UTC, ephathaway commented on mffpy/xml_files.py
> +    def acquisitionVersion(self):
I think this is the version of Net Station used to record the data.

2021-01-11 23:55 UTC, ephathaway approved these changes
Looks good! Thanks for adding those docstrings.

2021-01-12 10:02 UTC, merged