MAINT: Use FileNotFound rather than ValueError
BEL-Public/mffpy pull request #89
Opened 2021-06-03 13:08 UTC by larsoner

Opens a PR to address the comment in https://github.com/mne-tools/mne-python/pull/9406#discussion_r644197354, namely that trying to open a file that does not exist should raise FileNotFoundError rather than ValueError. In trying to test this, `pytest` failed for me, for two reasons:

1. The `mfz` file did not exist. Some sleuthing suggested that I needed to do `python ./bin/mff2mfz.py ./examples/example_1.mff`, but it seems cleaner just to do it automagically using pytest `conftest.py`, which is now implemented.
2. When I had some failures due to my changes, I'd get some failures *not* due to my changes because of poor test isolation in `test_writer.py`. Specfically, the use of `.cache` across a bunch of tests creates dependencies that can be problematic. Using the standard `tmpdir` pytest fixture is a clean, standard way to address this issue, so I implemented it.

I can revert these if you want, but in theory this should make it easier for your users (or CIs, if you want to implement them!) to do `pytest` and just have things work, and to iterate over tests more easily.

2021-06-03 15:37 UTC, ephathaway commented
> 1. The `mfz` file did not exist. Some sleuthing suggested that I needed to do `python ./bin/mff2mfz.py ./examples/example_1.mff`, but it seems cleaner just to do it automagically using pytest `conftest.py`, which is now implemented.

Running `make test` will create the necessary .mfz file.

2021-06-03 16:07 UTC, larsoner commented
> Running make test will create the necessary .mfz file.

I think the autouse fixture is a bit more standard, do you agree it's worth keeping the new way? If so I can clean up the makefile not to need this and people can just do `pytest` (or `make test`) and have everything work properly. If not, I can delete the autouse fixture

2021-06-03 16:43 UTC, ephathaway commented
> do you agree it's worth keeping the new way?

Yeah, let's keep it. I think this will make it a bit more user friendly.

2021-06-03 17:38 UTC, ephathaway commented
@larsoner, please take a look at https://github.com/larsoner/mffpy/pull/1. Thanks

2021-06-04 17:02 UTC, ephathaway requested changes
@larsoner can you go ahead and remove the `mff2mfz.py` call from the makefile? Then I think this is ready to merge.

2021-06-05 15:45 UTC, larsoner commented
I left the conversion target itself in there but removed the call to it in `make test`. Can remove the conversion target, too, if you prefer

2021-06-09 22:36 UTC, ephathaway commented
> I left the conversion target itself in there but removed the call to it in `make test`. Can remove the conversion target, too, if you prefer

I think the way you did it makes sense. Thanks. See https://github.com/larsoner/mffpy/pull/2 to address the GH workflow failure.

2021-06-10 17:43 UTC, larsoner commented
The pesky "workflow awaiting approval" box needs to clicked to get CIs to run here

2021-06-11 20:36 UTC, ephathaway approved these changes
Thanks @larsoner!

2021-06-11 20:36 UTC, merged